default_context:
  project_name: 'tracking-tools'
  project_slug: 'tracking-tools'
  domain_main: 'tracking-tools.com'
  domain_staging: 'stag.tracking-tools.com'
  docker_swarm_stack_name_main: 'tracking-tools-com'
  docker_swarm_stack_name_staging: 'stag-tracking-tools-com'
  secret_key: '4ebe3649b8b6dd1594132d900d1fb5ab132dd7ce71b0639e1de13d948fdcdcba'
  first_superuser: 'admin@tracking-tools.com'
  first_superuser_password: 'dedaad08283f059415b7023eb948ead9a76794d03cb0949068b943fde9965079'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.tracking-tools.com, https://stag.tracking-tools.com, https://tracking-tools.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@tracking-tools.com'
  couchbase_user: 'admin'
  couchbase_password: '23c778ee8022aa13d749c2d09c59625e951ef9fe5d49dc0748352bdb9168dbea'
  couchbase_sync_gateway_cors: 'http://localhost:4984, http://localhost:4985, http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, http://dev.tracking-tools.com, https://stag.tracking-tools.com, https://db.stag.tracking-tools.com, https://tracking-tools.com, https://db.tracking-tools.com, http://local.dockertoolbox.tiangolo.com, http://local.dockertoolbox.tiangolo.com:4984, http://localhost.tiangolo.com, http://localhost.tiangolo.com:4984'
  couchbase_sync_gateway_user: 'sync'
  couchbase_sync_gateway_password: 'cb8e301c499fd47d689dabe00cc7f0e785d34c2959f156609e410b0398203eb5'
  traefik_constraint_tag: 'tracking-tools.com'
  traefik_constraint_tag_staging: 'stag.tracking-tools.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:dedaad08283f059415b7023eb948ead9a76794d03cb0949068b943fde9965079'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  docker_image_sync_gateway: 'sync-gateway'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
