version: '3.3'
services:
  backend:
    depends_on: 
      - couchbase
  celeryworker:
    depends_on: 
      - couchbase
      - queue
  sync-gateway:
    depends_on:
      - couchbase
      - backend
