version: '3.3'
services:
  couchbase:
    ports:
      - '8091:8091'
  sync-gateway:
    ports:
      - '4984:4984'
      - '4985:4985'
  proxy:
    ports:
      - '80:80'
      - '8090:8080'
  flower:
    ports:
      - '5555:5555'
  backend:
    ports:
      - '8888:8888'
